#!/usr/bin/env bash
# OneCurve — flip active environment (dev | stage | prod)
#
#   ./scripts/flip-env.sh dev
#   ./scripts/flip-env.sh stage
#   ./scripts/flip-env.sh prod          # requires typing "prod"
#   ./scripts/flip-env.sh prod --yes    # CI / non-interactive
#   ./scripts/flip-env.sh status
#
# What it does:
#   1. Validates the target flags file
#   2. Writes platform/.env.active  (symlink-style pointer)
#   3. Merges config/env/<target>.env (if present) or .example into platform/.env
#   4. Exports NEXT_PUBLIC_OC_ENV + flags JSON for the storefront build
#   5. Prints a clear "you are on X" summary
#
# Secrets: copies only from config/env/<env>.env if YOU created it
# (gitignored). Templates stay as *.env.example.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TARGET="${1:-}"
FORCE_YES=0
[[ "${2:-}" == "--yes" || "${1:-}" == "--yes" ]] && FORCE_YES=1
[[ "${1:-}" == "--yes" ]] && TARGET="${2:-}"

usage() {
  cat <<EOF
Usage: ./scripts/flip-env.sh <dev|stage|prod|status> [--yes]

  dev    Local development (manual payments, seed OK)
  stage  Staging with Razorpay TEST keys
  prod   Production live keys — gated confirmation
  status Show current environment

After flip, restart services:
  Local:  ./dev.sh
  Docker: docker compose up -d --build
EOF
  exit 1
}

[[ -z "$TARGET" ]] && usage

active_env() {
  if [[ -f "$ROOT/.env.active" ]]; then
    # shellcheck disable=SC1091
    source "$ROOT/.env.active"
    echo "${OC_ENV:-unknown}"
  else
    echo "unset"
  fi
}

if [[ "$TARGET" == "status" ]]; then
  ENV_NOW="$(active_env)"
  echo "Active environment: $ENV_NOW"
  if [[ -f "$ROOT/config/flags/${ENV_NOW}.json" ]]; then
    echo "Flags file: config/flags/${ENV_NOW}.json"
    if command -v python3 >/dev/null 2>&1; then
      python3 - <<PY
import json
p="$ROOT/config/flags/${ENV_NOW}.json"
d=json.load(open(p))
f=d["flags"]
print(f"  razorpay={f['payments']['razorpay']} live_keys={f['payments']['razorpay_live_keys']} manual={f['payments']['manual_checkout']}")
print(f"  free_ship≥{f['commerce']['free_shipping_threshold']} bookkeeping={f['features']['bookkeeping']} badge={f['ops']['show_env_badge']}")
PY
    fi
  fi
  exit 0
fi

case "$TARGET" in
  dev|stage|prod) ;;
  *) usage ;;
esac

FLAGS_SRC="$ROOT/config/flags/${TARGET}.json"
[[ -f "$FLAGS_SRC" ]] || { echo "✗ Missing $FLAGS_SRC"; exit 1; }

# Validate JSON
python3 - <<PY
import json, sys
p="$FLAGS_SRC"
d=json.load(open(p))
assert d.get("env") == "$TARGET", f"flags.env mismatch: {d.get('env')}"
assert "flags" in d
print("✓ flags valid for $TARGET")
PY

if [[ "$TARGET" == "prod" && "$FORCE_YES" -ne 1 ]]; then
  echo ""
  echo "⚠  You are about to flip to PRODUCTION."
  echo "   This expects live Razorpay keys and disables manual checkout."
  read -r -p "Type 'prod' to continue: " CONFIRM
  [[ "$CONFIRM" == "prod" ]] || { echo "Aborted."; exit 1; }
fi

# Prefer local secret file over example
ENV_LOCAL="$ROOT/config/env/${TARGET}.env"
ENV_EXAMPLE="$ROOT/config/env/${TARGET}.env.example"
ENV_SRC=""
if [[ -f "$ENV_LOCAL" ]]; then
  ENV_SRC="$ENV_LOCAL"
  echo "✓ Using secrets from config/env/${TARGET}.env"
elif [[ -f "$ENV_EXAMPLE" ]]; then
  ENV_SRC="$ENV_EXAMPLE"
  echo "⚠ Using template config/env/${TARGET}.env.example"
  echo "  Copy to config/env/${TARGET}.env and fill secrets before real deploy."
else
  echo "✗ No env template for $TARGET"
  exit 1
fi

# Write pointer
cat > "$ROOT/.env.active" <<EOF
# Generated by scripts/flip-env.sh — do not edit by hand
OC_ENV=$TARGET
OC_FLAGS_FILE=config/flags/${TARGET}.json
EOF

# Build merged .env for docker-compose + tooling
{
  echo "# Generated by flip-env.sh for OC_ENV=$TARGET — $(date -u +%Y-%m-%dT%H:%MZ)"
  echo "# Source: ${ENV_SRC#$ROOT/}"
  echo ""
  cat "$ENV_SRC"
  echo ""
  echo "# --- injected by flip-env ---"
  echo "OC_ENV=$TARGET"
  echo "OC_FLAGS_FILE=config/flags/${TARGET}.json"
  # Compact flags for apps that read a single env var
  FLAGS_JSON="$(python3 -c "import json; print(json.dumps(json.load(open('$FLAGS_SRC'))['flags'], separators=(',',':')))")"
  echo "OC_FEATURE_FLAGS='$FLAGS_JSON'"
  echo "NEXT_PUBLIC_OC_ENV=$TARGET"
  echo "NEXT_PUBLIC_OC_FEATURE_FLAGS='$FLAGS_JSON'"
} > "$ROOT/.env"

# Also write storefront .env.local for Next (dev convenience)
mkdir -p "$ROOT/apps/storefront"
{
  echo "# Generated by flip-env.sh ($TARGET)"
  grep -E '^(NEXT_PUBLIC_|MEDUSA_BACKEND_URL|MEDUSA_PUBLISHABLE)' "$ROOT/.env" || true
  # Map compose-style names
  grep -E '^BACKEND_URL=' "$ROOT/.env" | sed 's/^BACKEND_URL=/NEXT_PUBLIC_MEDUSA_BACKEND_URL=/' || true
  grep -E '^STOREFRONT_URL=' "$ROOT/.env" | sed 's/^STOREFRONT_URL=/NEXT_PUBLIC_BASE_URL=/' || true
  grep -E '^MEDUSA_PUBLISHABLE_KEY=' "$ROOT/.env" | sed 's/^MEDUSA_PUBLISHABLE_KEY=/NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=/' || true
  echo "NEXT_PUBLIC_OC_ENV=$TARGET"
  echo "NEXT_PUBLIC_OC_FEATURE_FLAGS='$FLAGS_JSON'"
  echo "NEXT_PUBLIC_DEFAULT_REGION=in"
} > "$ROOT/apps/storefront/.env.local"

# Dev convenience: replace pk_*placeholder with the real key from local DB
if [[ "$TARGET" == "dev" ]]; then
  if "$ROOT/scripts/sync-publishable-key.sh" 2>/dev/null; then
    echo "✓ Synced real publishable key from database into storefront/.env.local"
  else
    echo "⚠ Storefront still has a placeholder publishable key."
    echo "  After backend is up:  ./scripts/sync-publishable-key.sh"
  fi
fi

# Backend .env merge helper (keep existing DATABASE_URL if present and target is dev)
if [[ -f "$ROOT/apps/backend/.env" && "$TARGET" == "dev" ]]; then
  echo "✓ Left apps/backend/.env in place (dev); platform/.env is source for docker"
else
  {
    echo "# Generated by flip-env.sh ($TARGET)"
    cat "$ROOT/.env"
  } > "$ROOT/apps/backend/.env.generated"
  echo "  wrote apps/backend/.env.generated (merge into .env as needed)"
fi

echo ""
echo "════════════════════════════════════════════"
echo "  OneCurve environment → $TARGET"
echo "════════════════════════════════════════════"
python3 - <<PY
import json
d=json.load(open("$FLAGS_SRC"))
f=d["flags"]
print(f"  payments.razorpay        = {f['payments']['razorpay']}")
print(f"  payments.razorpay_live   = {f['payments']['razorpay_live_keys']}")
print(f"  payments.manual          = {f['payments']['manual_checkout']}")
print(f"  free_shipping_threshold  = ₹{f['commerce']['free_shipping_threshold']}")
print(f"  bookkeeping              = {f['features']['bookkeeping']}")
print(f"  show_env_badge           = {f['ops']['show_env_badge']}")
print(f"  e2e_hooks                = {f['ops']['e2e_hooks']}")
PY
echo ""
echo "Next:"
echo "  status:  ./scripts/flip-env.sh status"
echo "  local:   ./dev.sh"
echo "  docker:  docker compose --env-file .env up -d --build"
echo "  e2e:     npm run test:e2e -w @dtc/e2e   (after stack is up)"
echo ""
